version: "3.8"

services:
  n8n:
    image: n8n-custom
    container_name: video_dl
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - TZ=Europe/Paris
      # IMPORTANT : autoriser tous les nodes standards
      - NODES_EXCLUDE=[]
    volumes:
      - video_datas:/home/node/.n8n
      - ./data:/data
    restart: unless-stopped

volumes:
  video_datas:
